import React, { useState, useEffect } from 'react';
import { UserProfile, CreditBureau, AIConsultation } from './types';
import { Navbar } from './components/Navbar';
import { ScoreGauge } from './components/ScoreGauge';
import { CreditPillars } from './components/CreditPillars';
import { AIConsultationView } from './components/AIConsultationView';
import { ScoreJourneyView } from './components/ScoreJourneyView';
import { DebtPayoffView } from './components/DebtPayoffView';
import { OnboardingModal } from './components/OnboardingModal';
import { formatINR, calculateFinancialMetrics, getCreditTier } from './utils/creditCalculator';
import { 
  Sparkles, 
  TrendingUp, 
  CreditCard, 
  PlusCircle, 
  ShieldCheck, 
  ArrowRight, 
  CheckCircle2, 
  AlertTriangle,
  Building2,
  Calendar,
  Layers,
  Award
} from 'lucide-react';

export default function App() {
  const [currentUser, setCurrentUser] = useState<UserProfile | null>(null);
  const [usersList, setUsersList] = useState<{ id: string; fullName: string; currentScore: number; bureau: CreditBureau }[]>([]);
  const [currentTab, setCurrentTab] = useState<'overview' | 'ai-advisor' | 'journey' | 'payoff' | 'onboard'>('overview');
  const [bureau, setBureau] = useState<CreditBureau>('CIBIL');
  const [consultation, setConsultation] = useState<AIConsultation | null>(null);
  const [isConsultationLoading, setIsConsultationLoading] = useState(false);
  const [isOnboardingOpen, setIsOnboardingOpen] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => {
      setToastMessage(null);
    }, 6000);
  };

  // Fetch initial users list
  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      const res = await fetch('/api/users');
      if (res.ok) {
        const list = await res.json();
        setUsersList(list);
        if (list.length > 0 && !currentUser) {
          loadUser(list[0].id);
        }
      }
    } catch (err) {
      console.error('Failed to fetch users', err);
    }
  };

  const loadUser = async (userId: string) => {
    try {
      const res = await fetch(`/api/user/${userId}`);
      if (res.ok) {
        const user = await res.json();
        setCurrentUser(user);
        setBureau(user.bureau || 'CIBIL');
        setConsultation(user.lastAiConsultation || null);
      }
    } catch (err) {
      console.error('Failed to load user', err);
    }
  };

  // Trigger Gemini AI consultation
  const triggerAiConsultation = async () => {
    if (!currentUser) return;
    setIsConsultationLoading(true);
    try {
      const res = await fetch('/api/ai/consultation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId: currentUser.id }),
      });
      if (!res.ok) throw new Error('AI Consultation failed');
      const data = await res.json();
      setConsultation(data);
      showToast('AI Consultation and 5-Step Indian Roadmap successfully generated by Gemini 3.8 Flash!');
    } catch (err: any) {
      alert(err.message || 'AI consultation could not be generated.');
    } finally {
      setIsConsultationLoading(false);
    }
  };

  const handleUpdateRoadmapStep = (stepNumber: number, isCompleted: boolean) => {
    if (!consultation) return;
    const updated = {
      ...consultation,
      fiveStepRoadmap: consultation.fiveStepRoadmap.map(s => 
        s.stepNumber === stepNumber ? { ...s, isCompleted } : s
      ),
    };
    setConsultation(updated);
    showToast(`Roadmap step ${stepNumber} marked as ${isCompleted ? 'Completed' : 'Pending'}`);
  };

  const handlePayoffSuccess = (result: any) => {
    if (result.updatedUser) {
      setCurrentUser(result.updatedUser);
      showToast(
        `Scenario 4 Success: Paid off debt! Credit score jumped +${result.scoreDelta} pts (${result.previousScore} → ${result.newScore}) and card utilization dropped to ${result.newUtilization}%!`
      );
    }
  };

  // Scenario quick launchers
  const handleRunScenario = async (scenarioNum: number) => {
    if (scenarioNum === 1) {
      // Scenario 1: User Onboarding and Initial Assessment
      setIsOnboardingOpen(true);
      showToast('Scenario 1 Active: Register a borrower or test live DTI & FOIR calculations in real-time.');
    } else if (scenarioNum === 2) {
      // Scenario 2: AI-Powered Financial Consultation (Fair score borrower Suyog Belote)
      const suyog = usersList.find(u => u.fullName.includes('Suyog')) || usersList[0];
      if (suyog) {
        await loadUser(suyog.id);
        setCurrentTab('ai-advisor');
        showToast('Scenario 2 Active: Suyog Belote loaded (Fair Score: 648). Generating Gemini 3.8 Flash Consultation...');
        setTimeout(() => {
          triggerAiConsultation();
        }, 300);
      }
    } else if (scenarioNum === 3) {
      // Scenario 3: Progress Tracking via Data Visualization (Rahul's multi-month trajectory)
      const rahul = usersList.find(u => u.fullName.includes('Rahul')) || usersList[1];
      if (rahul) {
        await loadUser(rahul.id);
        setCurrentTab('journey');
        showToast('Scenario 3 Active: Rahul Verma loaded (6-month trajectory: 628 → 758 Excellent score).');
      }
    } else if (scenarioNum === 4) {
      // Scenario 4: Real-time Credit Health Monitoring & Debt Payoff
      const suyog = usersList.find(u => u.fullName.includes('Suyog')) || usersList[0];
      if (suyog) {
        await loadUser(suyog.id);
        setCurrentTab('payoff');
        showToast('Scenario 4 Active: Pay off HDFC card or Axis loan to watch live score recalculation and utilization update!');
      }
    }
  };

  if (!currentUser) {
    return (
      <div className="min-h-screen bg-slate-950 text-slate-100 flex items-center justify-center">
        <div className="flex flex-col items-center gap-3">
          <div className="w-10 h-10 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
          <span className="text-sm font-semibold text-slate-300">Loading Credit Assistant...</span>
        </div>
      </div>
    );
  }

  const metrics = calculateFinancialMetrics(currentUser);
  const tier = getCreditTier(currentUser.currentScore);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col antialiased selection:bg-emerald-500/20 selection:text-emerald-300">
      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-5 right-5 z-50 max-w-md bg-slate-900 border border-emerald-500/50 shadow-2xl rounded-2xl p-4 flex items-start gap-3 animate-slide-up">
          <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
          <div className="text-xs text-slate-200">
            <span className="font-bold text-white block mb-0.5">Platform Update</span>
            <p className="leading-relaxed">{toastMessage}</p>
          </div>
        </div>
      )}

      {/* Main Navigation */}
      <Navbar
        currentTab={currentTab}
        setCurrentTab={setCurrentTab}
        currentUser={currentUser}
        usersList={usersList}
        onSelectUser={loadUser}
        onOpenOnboarding={() => setIsOnboardingOpen(true)}
        bureau={bureau}
        onChangeBureau={(newBureau) => {
          setBureau(newBureau);
          setCurrentUser(prev => prev ? { ...prev, bureau: newBureau } : null);
        }}
        onRunScenario={handleRunScenario}
      />

      {/* Main View Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        {/* TAB 1: OVERVIEW DASHBOARD */}
        {currentTab === 'overview' && (
          <div className="space-y-8">
            {/* Top User Summary & Score Gauge */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              {/* Left Profile Info */}
              <div className="lg:col-span-7 bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl relative overflow-hidden">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
                  <div>
                    <span className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">
                      Verified Borrower Profile
                    </span>
                    <h1 className="text-2xl font-extrabold text-white tracking-tight mt-0.5">
                      {currentUser.fullName}
                    </h1>
                    <p className="text-xs text-slate-400 mt-1">
                      {currentUser.city} · {currentUser.email}
                    </p>
                  </div>

                  <div className="flex items-center gap-2">
                    <span className={`text-xs font-bold px-3 py-1 rounded-full border ${tier.bgBadge}`}>
                      {tier.label}
                    </span>
                  </div>
                </div>

                {/* Financial Health High-Level KPIs */}
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3.5 mt-5">
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800">
                    <span className="text-[11px] text-slate-400 font-medium">Monthly Gross Salary</span>
                    <p className="text-base font-bold font-mono text-white mt-1">
                      {formatINR(metrics.grossIncome)}
                    </p>
                  </div>
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800">
                    <span className="text-[11px] text-slate-400 font-medium">Monthly Living Expenses</span>
                    <p className="text-base font-bold font-mono text-slate-300 mt-1">
                      {formatINR(currentUser.monthlyLivingExpenses)}
                    </p>
                  </div>
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 col-span-2 sm:col-span-1">
                    <span className="text-[11px] text-slate-400 font-medium">Net Disposable Savings</span>
                    <p className="text-base font-bold font-mono text-emerald-400 mt-1">
                      {formatINR(metrics.netSavings)}/mo
                    </p>
                  </div>
                </div>

                {/* Quick Indian Banking Action Strip */}
                <div className="mt-5 pt-4 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-3 text-xs">
                  <div className="flex items-center gap-2 text-slate-300">
                    <ShieldCheck className="w-4 h-4 text-emerald-400" />
                    <span>Interest Rate Assessment: <strong className="text-white">{tier.interestRateImpact}</strong></span>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => setCurrentTab('ai-advisor')}
                      className="text-emerald-400 hover:text-emerald-300 font-semibold cursor-pointer flex items-center gap-1"
                    >
                      <span>AI Consultation</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              </div>

              {/* Right: SVG Score Speedometer */}
              <div className="lg:col-span-5">
                <ScoreGauge
                  score={currentUser.currentScore}
                  bureau={bureau}
                  previousScore={
                    currentUser.scoreHistory.length > 1
                      ? currentUser.scoreHistory[currentUser.scoreHistory.length - 2].score
                      : undefined
                  }
                  onRunAiConsultation={() => {
                    setCurrentTab('ai-advisor');
                    triggerAiConsultation();
                  }}
                />
              </div>
            </div>

            {/* 5 Credit Pillars & Bottleneck Cards */}
            <CreditPillars
              user={currentUser}
              onOpenPayoff={() => setCurrentTab('payoff')}
              onOpenAiConsult={() => {
                setCurrentTab('ai-advisor');
                triggerAiConsultation();
              }}
            />

            {/* Active Credit Accounts Overview (Credit Cards & Active Loans) */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              {/* Credit Cards Card */}
              <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <CreditCard className="w-5 h-5 text-emerald-400" />
                    <h3 className="text-base font-bold text-white">Active Credit Cards</h3>
                  </div>
                  <span className="text-xs font-mono text-slate-400">
                    Util: {metrics.utilizationPercent}%
                  </span>
                </div>

                <div className="space-y-3">
                  {currentUser.creditCards.map(c => {
                    const cardUtil = c.creditLimit > 0 ? Math.round((c.currentBalance / c.creditLimit) * 100) : 0;
                    return (
                      <div key={c.id} className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800 text-xs">
                        <div className="flex items-center justify-between font-bold text-white">
                          <span>{c.bankName} - {c.cardName}</span>
                          <span className={`font-mono ${cardUtil > 30 ? 'text-rose-400' : 'text-emerald-400'}`}>
                            {cardUtil}% util
                          </span>
                        </div>
                        <div className="flex items-center justify-between text-slate-400 mt-2">
                          <span>Balance: <strong className="text-white font-mono">{formatINR(c.currentBalance)}</strong></span>
                          <span>Limit: <strong className="text-slate-300 font-mono">{formatINR(c.creditLimit)}</strong></span>
                        </div>
                        <div className="w-full bg-slate-800 h-1 rounded-full mt-2 overflow-hidden">
                          <div
                            className={`h-full rounded-full ${cardUtil > 50 ? 'bg-rose-500' : cardUtil > 30 ? 'bg-amber-500' : 'bg-emerald-500'}`}
                            style={{ width: `${Math.min(100, cardUtil)}%` }}
                          />
                        </div>
                      </div>
                    );
                  })}
                </div>

                <div className="mt-4 pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs">
                  <span className="text-slate-400">Total Cards Debt: {formatINR(metrics.totalCardBalance)}</span>
                  <button
                    onClick={() => setCurrentTab('payoff')}
                    className="text-emerald-400 hover:underline font-semibold cursor-pointer"
                  >
                    Pay Off Cards &rarr;
                  </button>
                </div>
              </div>

              {/* Active Loans Card */}
              <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Building2 className="w-5 h-5 text-emerald-400" />
                    <h3 className="text-base font-bold text-white">Active Loan Facilities</h3>
                  </div>
                  <span className="text-xs font-mono text-slate-400">
                    EMI: {formatINR(metrics.totalLoanEmi)}/mo
                  </span>
                </div>

                <div className="space-y-3">
                  {currentUser.loans.map(l => (
                    <div key={l.id} className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800 text-xs">
                      <div className="flex items-center justify-between font-bold text-white">
                        <div className="flex items-center gap-2">
                          <span>{l.lenderName}</span>
                          <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-800 text-slate-300">
                            {l.loanType}
                          </span>
                        </div>
                        <span className={`text-[11px] px-2 py-0.5 rounded ${
                          l.status === 'CLOSED'
                            ? 'bg-slate-800 text-slate-400'
                            : 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30'
                        }`}>
                          {l.status}
                        </span>
                      </div>
                      <div className="flex items-center justify-between text-slate-400 mt-2">
                        <span>Outstanding: <strong className="text-white font-mono">{formatINR(l.outstandingBalance)}</strong></span>
                        <span>EMI: <strong className="text-slate-300 font-mono">{formatINR(l.monthlyEmi)}/mo</strong></span>
                      </div>
                      <div className="text-[10px] text-slate-500 mt-1 flex justify-between">
                        <span>Interest Rate: {l.interestRate}% p.a.</span>
                        <span>Remaining: {l.tenureMonthsRemaining} mos</span>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-4 pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs">
                  <span className="text-slate-400">Total Loan Principal: {formatINR(metrics.totalLoanBalance)}</span>
                  <button
                    onClick={() => setCurrentTab('payoff')}
                    className="text-emerald-400 hover:underline font-semibold cursor-pointer"
                  >
                    Prepay Loans &rarr;
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: AI CONSULTATION & 5-STEP ROADMAP (Scenario 2) */}
        {currentTab === 'ai-advisor' && (
          <AIConsultationView
            user={currentUser}
            consultation={consultation}
            isLoading={isConsultationLoading}
            onTriggerConsultation={triggerAiConsultation}
            onUpdateConsultationStep={handleUpdateRoadmapStep}
          />
        )}

        {/* TAB 3: CREDIT SCORE JOURNEY & CHARTS (Scenario 3) */}
        {currentTab === 'journey' && (
          <ScoreJourneyView user={currentUser} />
        )}

        {/* TAB 4: REAL-TIME DEBT PAYOFF & SIMULATOR (Scenario 4) */}
        {currentTab === 'payoff' && (
          <DebtPayoffView
            user={currentUser}
            onPayoffSuccess={handlePayoffSuccess}
          />
        )}
      </main>

      {/* Onboarding & Initial Assessment Modal (Scenario 1) */}
      <OnboardingModal
        isOpen={isOnboardingOpen}
        onClose={() => setIsOnboardingOpen(false)}
        onSuccess={(newUser) => {
          setCurrentUser(newUser);
          fetchUsers();
          setCurrentTab('overview');
          showToast(`Scenario 1 Complete: Borrower "${newUser.fullName}" registered. DTI and initial assessment calculated!`);
        }}
      />

      {/* Indian Banking Compliance Footer */}
      <footer className="w-full border-t border-slate-800/80 bg-slate-950 py-6 px-4 mt-auto text-xs text-slate-500">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-center sm:text-left">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
            <span className="font-semibold text-slate-300">Credit Assistant (India)</span>
            <span>· RBI Fair Lending & CIBIL/Experian Scoring Guidelines</span>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-4 text-slate-400">
            <span>Scale: 300 - 900</span>
            <span>·</span>
            <span>FOIR Benchmark: &lt; 40%</span>
            <span>·</span>
            <span>Utilization Target: &lt; 30%</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
